- hosts: localhost
  roles:
    - base
    - role: gantsign.oh-my-zsh
      users:
        - username: '{{ primary_user }}'
    - nvim
    - role: avanov.pyenv 
      pyenv_path: $HOME/pyenv
      pyenv_owner: "{{ primary_user }}"
      pyenv_global: "system"
      pyenv_python_versions:
        - "3.7.4"
        - "2.7.8"
      pyenv_virtualenvs:
        - venv_name: "latest_v3"
          py_version: "3.7.4"
        - venv_name: "latest_v2"
          py_version: "2.7.8"
  vars_files: ~/projects/ansible_vars/vars.yml
