- name: install basic packages
  package:
    name: '{{ item }}'
  with_items:
    - '{{ base_formulae }}'

- name: tap casks
  homebrew_tap:
    name: '{{ item }}'
  with_items:
    - '{{ base_taps }}'

- name: install homebrew casks
  homebrew_cask:
    name: '{{ item }}'
  with_items:
    - '{{ base_casks }}'
