- name: install basic packages
  package:
    name: '{{ item }}'
  with_items:
    - fzf

- name: tap casks
  homebrew_tap:
    name: '{{ item }}'
  with_items:
    - homebrew/cask-drivers

- name: install homebrew casks
  homebrew_cask:
    name: '{{ item }}'
  with_items:
    - powershell
    - logitech-options
